# Generated by Django 6.0 on 2026-01-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_host_approved',
            field=models.BooleanField(default=False),
        ),
    ]
