# Generated by Django 6.0 on 2026-01-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_avaialble',
            new_name='is_available',
        ),
    ]
